"""add runtime tables

Revision ID: 845c3c8bb11f
Revises: 8ebcdb2a87f6
Create Date: 2026-03-04 00:02:17.490030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845c3c8bb11f'
down_revision: Union[str, Sequence[str], None] = '8ebcdb2a87f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
